#!/bin/sh

. slib

help() {
cat << EOF
${0}: Wrapper script to take screenshots
options:
 -d [File]       Write to File
 -s              Select the area with the cursor
 -h              Print this message and exit

NOTE: save directory is ~/pics/screenshot
EOF

exit 0
}

check_program "scrot"

default_dir="${XDG_SCREENSHOT_DIR:-${HOME}/media/photo/screenshot}"

s_flg=""
while getopts "d:sh" option; do
	case "${option}" in
	d) input="${OPTARG}" ;;

	s) s_flg="1" ;;

	h) help ;;

	*) invalid_use -h ;;

	esac
done

shift $((OPTIND - 1))

[ ${#} != 0 ] && invalid_use

if [ -z "${input}" ]; then
	input="${default_dir}"
	mkdir -p "${default_dir}"
fi

outfile="${input}"

[ -d "${input}" ] && outfile="${input}/$(date '+%b%d::%H%M%S').png"

if [ ! -e "$(dirname "${outfile}")" ]; then
	mkdir -p "$(dirname "${outfile}")" > /dev/null 2>&1 \
	|| err "Failed to create directory"
fi

if [ "${s_flg}" = "1" ]; then
	run --reload-compositor "scrot -zs ${outfile}" "${outfile}"
else
	run "scrot -z ${outfile}" "${outfile}"
fi
