#!/bin/sh

. slib

help() {
cat << EOF
${0}: Wrapper script to set lock the screen
EOF

exit 0
}

check_program "slock"

[ "${#}" -eq 1 ] && [ "${1}" = "-h" ] && help

[ "${#}" != 0 ] && invalid_use

BACKGROUND="${XDG_CACHE_HOME:-$HOME/.cache}/wallpaper/current"
slock -f "${BACKGROUND}"
