# Minimal bash config for servers
set -o vi
stty -ixon # Disable ctrl-s and ctrl-q for freezing prompt
shopt -s autocd # automatically cd into typed directory

alias vi=vim
alias vi=nvim

PS1='\u@\H \w\[\e[0;$(($?==0?0:91))m\] % \[\e[0m\]'
