#!/bin/sh

. "lib_common.sh"

help() {
cat << EOF
${0}: Replace all the spaces in file and directory
names with "_" in in the current directory.
options:
 -h              Print this message and exit
EOF
exit 0
}

[ "${1}" = "-h" ] && help

[ ${#} -gt 0 ] && invalid_use

for file in ./*; do
	newfile=$(echo "${file}" | tr ' ' '_')
	[ "${newfile}" != "${file}" ] && mv -v "${file}" "${newfile}"
done

exit 0
