#!/bin/sh

. slib

help() {
cat << EOF
${0}: Open links from bookmarks through dmenu
options:
[link]		Open link
 -h 		Print this message and exit

NOTE: bookmarks file is located at ~/.config/sites/bookmarks
EOF

exit 0
}

alias dmenucmd="dmenu -bw 1 -c -g 1 -l 25"

[ -z "${BROWSER}" ] && browser="qutebrowser" || browser="${BROWSER}"

if [ "${#}" -eq 0 ]; then

	# FIXME: Use XDG_CONFIG
	link_file="${HOME}/.config"/sites/bookmarks.txt

	check_program "dmenu"

	[ -z "${XDG_HOME_CONFIG}" ] || link_file="${XDG_HOME_CONFIG}"/sites/bookmarks.txt
	[ -e "${link_file}" ] || err "Couldn't find bookmarks file"

	link=$(< "${link_file}" dmenucmd)

	[ -z "${link}" ] || "${browser}" "${link}"

elif [ "${#}" -eq 1 ]; then 
	[ "${1}" = "-h" ] && help 

	"${browser}" "${1}"
else
	invalid_use
fi
