#!/bin/sh

help() {
cat << EOF
${0}: Open given in the browser.
options:
 -l [link]	Open link
 -h 		Print this message and exit
EOF
}

err() {
	for line in "${@}"; do
		echo "${line}" >&2
	done
	exit 1
}

check_dmenu() {
	if ! command -v dmenu > /dev/null 2>&1; then
		err "${0}: dmenu must be installed"
	fi
}

#TODO check if browser environmental variable exists
#TODO check if ~/.config/sites/bookmarks.txt
browser=$BROWSER
links_file=~/.config/sites/bookmarks.txt


if [ "${#}" -eq 0 ]; then
	cat "${links_file}" | dmenu | xargs "${browser}"

elif [ "${#}" -eq 1 ]; then 
	[ "${1}" == "-h" ] && help && exit 0
	"${browser}" "${1}"
else
	err "invalid usage"
fi
