#!/bin/sh

. slib

help() {
cat << EOF
${0}: Wrapper script to send notifications

options:
 -s [Name] [Msg]	Send Msg with Name
 -s [Msg]		Send Msg Without Name
 -h 			Print this message and exit
EOF

exit 0
}

check_program "notify-send" "dunst must be installed"

case "${1}" in
"-s")
	[ "${#}" -gt 3 ] && invalid_use

	run "notify-send ${2} ${3}"

	exit 0
;;
"-h") help ;;

*) invalid_use ;;

esac
