#!/bin/sh

. slib

help() {
cat << EOF
${0}: Qemu Wrapper, very simple script for abriviating \
verbose qemu commands and options

options:
 -c			create an Image.img with 10G space
 -r [input.iso]		run input.iso
 -x [input.qcow2]	run input.qcow2
EOF

exit 0
}

check_program "qemu-img"
check_program "qemu-system-x86_64"

[ $# != 2 ] && [  $# != 1 ] && invalid_use

while getopts "cr:x:h" option ;do
	case "${option}" in
	c) run "qemu-img create -f qcow2 Image.img 10G" ;;

	x) run "qemu-system-x86_64 -drive file=${OPTARG},format=qcow2 -enable-kvm" ;;

	r)
		run "qemu-system-x86_64 -enable-kvm -cdrom ${OPTARG} \
			-boot menu=on -drive file=Image.img -m 4G"
	;;
	h) help ;;

	*) invalid_use -h ;;

	esac
done

# Unreachable
invalid_use
