#!/bin/sh

. slib

check_program "ollama"

if [ "${1}" = "-s" ]; then
	addition="answer in a short way:"
	shift
fi

question="${addition} ${@}"
model="codellama"

echo "${question}" | ollama run "${model}"
