#!/bin/sh

help() {
cat << EOF
$0: Wrapper script to set wallpapers

options:
 -d [File]	Select a wallpaper or a directory
 -h 		Print this message and exit
 -c 		Remove the current wallpaper

NOTE: default wallpaper directory is ~/.config/wallpapers
EOF
}

err() {
	echo "$*" >&2
	exit 1
}

run() {
	if ! ${1} > /dev/null 2>&1; then
		err "${2}"
	fi
}

if ! command -v xwallpaper > /dev/null 2>&1; then
	err "${0}: xwallpaper must be installed"
fi

if [ $# != 0 ] && [ $# != 1 ] && [ $# != 2 ]; then
	err "${0}: Invalid usage
Try '$0 -h' for help."
fi


waldir="${HOME}"/.config/wallpapers

while getopts "hcd:" option; do
	case "${option}" in
	c)
		run "xwallpaper --clear" \
		"${0}: Failed to clear wallpaper"
		exit 0
	;;
	d) buf="${OPTARG}" ;;

	h) help; exit 0 ;;

	*) err "Try '${0} -h' for help" ;;
	esac
done


if [ -n "${buf}" ]; then
	case $(file -b --mime-type "${buf}") in
	image/*) image="${buf}" ;;

	inode/directory) waldir="${buf}" ;;

	*) err "Couldn't read given file" ;;
	esac
fi

if [ -z "${image}" ]; then
	image=$(find "${waldir}" -iregex '.*\.jpeg\|.*\.jpng\|.*\.png' 2>/dev/null \
	| shuf -n 1 )
fi

run "xwallpaper --zoom ${image}" \
"${0}: Failed to set wallpaper"

echo "${image}"
