#!/bin/sh

userresources="${XDG_CONFIG_HOME:-${HOME}/.config}/x11/xresources"

# merge in defaults and keymaps
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

dunst &
picom &
dcheck_battery &
dcheck_mail &
setxkbmap -option "caps:ctrl_modifier"                  # Map Caps Lock to Ctrl
setxkbmap us                                            # Set US keyboard layout
slstatus &
unclutter &                                             # Hide mouse cursor if inactive
xgamma -gamma 0.8                                       # Change gamma
swall -d "${DATADIR:-${HOME}/.local/share}/wallpapers"  # Set a wallpaper
xset r rate 300 50                                      # Increase cursor speed
xset s off && xset -dpms                                # Disable screen blackening

exec dwm
