#!/bin/sh

userresources="$HOME/.config/x11/xresources"

# merge in defaults and keymaps
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

setxkbmap -option "caps:ctrl_modifier" # change caps_lock to ctrl
xset r rate 300 50                     # increase cursor speed
xset s off && xset -dpms               # disable screen blackening
xgamma -gamma 0.8                      # change gamma
swall                                  # set wallpaper
dunst &
picom &
slstatus &
exec dwm
